# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miniecs < Formula
  desc "Miniecs: AWS ECS Login, Exec CLI"
  homepage "https://github.com/jedipunkz/miniecs"
  version "1.6.7"

  on_macos do
    on_intel do
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.7/miniecs_1.6.7_darwin_amd64.tar.gz"
      sha256 "edcd04103541196b8ba80ffbc5f568cc6f5142c9291ca87f7fb0916ef80651db"

      def install
        bin.install "miniecs"
      end
    end
    on_arm do
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.7/miniecs_1.6.7_darwin_arm64.tar.gz"
      sha256 "10e434c058f778c9fa16d22892aa010df62992ec22c4fb0cbb32e44f6719a9c3"

      def install
        bin.install "miniecs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.7/miniecs_1.6.7_linux_amd64.tar.gz"
        sha256 "16037f520618e94b36908b6b97efa9040aa9eb44b9481efcbf5128a6eda81a74"

        def install
          bin.install "miniecs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.7/miniecs_1.6.7_linux_armv6.tar.gz"
        sha256 "9b9c50000a845340fba89de67d1feb10441a5c4cf5a52ea9fdd7e5157a0c6219"

        def install
          bin.install "miniecs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.7/miniecs_1.6.7_linux_arm64.tar.gz"
        sha256 "7fce1efc440b8f46b8773edc389c7fd205afebf65c4501a3977ca92ac4d5c512"

        def install
          bin.install "miniecs"
        end
      end
    end
  end

  test do
    system "${bin}/miniecs --help"
  end
end
