# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miniecs < Formula
  desc "Miniecs: AWS ECS Login, Exec CLI"
  homepage "https://github.com/jedipunkz/miniecs"
  version "2.0.1"

  on_macos do
    on_intel do
      url "https://github.com/jedipunkz/miniecs/releases/download/v2.0.1/miniecs_2.0.1_darwin_amd64.tar.gz"
      sha256 "121a78bd1129de27be7746a74a2515159a475d2936da0b10ece9dba9c90cf929"

      def install
        bin.install "miniecs"
      end
    end
    on_arm do
      url "https://github.com/jedipunkz/miniecs/releases/download/v2.0.1/miniecs_2.0.1_darwin_arm64.tar.gz"
      sha256 "5fb2000cfcf205ce49bcdc53b991185e6d6ee99eb6b8fb035e93477de6dcf4ab"

      def install
        bin.install "miniecs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jedipunkz/miniecs/releases/download/v2.0.1/miniecs_2.0.1_linux_amd64.tar.gz"
        sha256 "6a675f58495a809dfc285f730b15d26e28b0017c04bb64de84bc6ee984f47894"

        def install
          bin.install "miniecs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/jedipunkz/miniecs/releases/download/v2.0.1/miniecs_2.0.1_linux_armv6.tar.gz"
        sha256 "0f928d085620fc8c767b6b9b2ec8782e93cb796a4f4ab9de4a90633b18a3c2bd"

        def install
          bin.install "miniecs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jedipunkz/miniecs/releases/download/v2.0.1/miniecs_2.0.1_linux_arm64.tar.gz"
        sha256 "caf7bebedc9447a32a1f0f46d68d29cd14969259050c705d5c4e565b2bbc0303"

        def install
          bin.install "miniecs"
        end
      end
    end
  end

  test do
    system "${bin}/miniecs --help"
  end
end
