# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miniecs < Formula
  desc "AWS ECS Login, Exec CLI"
  homepage "https://github.com/jedipunkz/miniecs"
  version "1.6.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.1/miniecs_1.6.1_darwin_arm64.tar.gz"
      sha256 "b02bb70f81fe86f88fcf5954fd304e98752b2d396c933df98a6fa67e2cd60c02"

      def install
        bin.install "miniecs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.1/miniecs_1.6.1_darwin_amd64.tar.gz"
      sha256 "b296f1439540c49cc3de6680c5ad1adce4739a8a565d414858371d9390203925"

      def install
        bin.install "miniecs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.1/miniecs_1.6.1_linux_amd64.tar.gz"
      sha256 "196c769af8ab57b39ce400fb696ca44c1d3990bde4a6747ccf904d6e0e5e8b08"

      def install
        bin.install "miniecs"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.1/miniecs_1.6.1_linux_armv6.tar.gz"
      sha256 "2fcbdb4de9e395690133e7e298359a30582c49bac0fc5831731d00c83ad3b16e"

      def install
        bin.install "miniecs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.6.1/miniecs_1.6.1_linux_arm64.tar.gz"
      sha256 "97855073ab168560632362c54e64f0e7b1d8f77398aabf74215dda0891b3a457"

      def install
        bin.install "miniecs"
      end
    end
  end

  test do
    system "${bin}/miniecs --help"
  end
end
