# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miniecs < Formula
  desc "AWS ECS Login, Exec CLI"
  homepage "https://github.com/jedipunkz/miniecs"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.4.0/miniecs_1.4.0_darwin_arm64.tar.gz"
      sha256 "05442c252540da3f9bf7d5dcb90f60f028df30b21cb9c21e19c66449e5cb769c"

      def install
        bin.install "miniecs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.4.0/miniecs_1.4.0_darwin_amd64.tar.gz"
      sha256 "25e9abcd79a2eb4635d69408f2bf1bde10281c04054b32e4236b9c0b6e21150e"

      def install
        bin.install "miniecs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.4.0/miniecs_1.4.0_linux_amd64.tar.gz"
      sha256 "f6cc1c8cc5d53e841c41d419e758d5d3d6652f76295312b28f4ef6b13bff6d1e"

      def install
        bin.install "miniecs"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.4.0/miniecs_1.4.0_linux_armv6.tar.gz"
      sha256 "46a8f17010c6558001a0ec1c59dc19317aeb6ce281c6064014647fb71b4e9f4a"

      def install
        bin.install "miniecs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedipunkz/miniecs/releases/download/v1.4.0/miniecs_1.4.0_linux_arm64.tar.gz"
      sha256 "7d43828bfadd0246aabaf760c1ddacfc5ebbbd902bc21144367b2c705ff605dc"

      def install
        bin.install "miniecs"
      end
    end
  end

  test do
    system "${bin}/miniecs --help"
  end
end
